apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: example
  labels:
    alertmanagerconfig: enabled
spec:
  route:
    receiver: "null"
    groupBy: [ 'alertname' ]
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 15m
    routes:
      - match:
          team: devs
          new: "true"
        receiver: "devs"
      - match:
          team: infra
          new: "true"
        receiver: "infra"
  receivers:
    - name: "null"
    - name: "devs"
      emailConfigs:
        - to: devs@cpas.cz
          from: noreply-monitoring@cpas.cz
          smarthost: maildev-smtp
    - name: "infra"
      emailConfigs:
        - to: infra@cpas.cz
          from: noreply-monitoring@cpas.cz
          smarthost: maildev-smtp
